name: spacedata
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - lightgbm=3.3.5
  - pip
  - pip:
    - vowpalwabbit
    - imodels
    - catboost
    - xgboost
    - fastai
    - ray[tune]
    - pyDataverse==0.3.1
    - networkx
    - hydra-core==1.3.2
    - pytorch_lightning==1.2
    - autogluon.tabular
    - ipykernel
    - black
