name: spacetrain
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - lightgbm=3.3.5
  - geopandas=0.9.0
  - matplotlib=3.7.1
  - jupyter
  - notebook
  - pytorch:pytorch
  - lightning=2.0.2
  - pip
  - pip:
    - autogluon==0.7.0
    - pyDataverse==0.3.1
    - networkx==2.8.8
    - tqdm==4.65.0
    - hydra-core==1.3.2
    - bokeh==2.0.1

