defaults:
  - _self_
  - data:

data:
  base_name: ???
  path: ???
  confounder: null
  outcome: ???
  treaments: ???
  index_col: null # can overwrite
  treatment_bins: ???  # if 2, then assumed binary
  graph_path: ???
  has_coordinates: ???

  scaling:  # scaling done before transforms
    outcome:  # unit, standard
    treatment:  # unit, standard

  transforms:
    outcome:   # log, symlog, logit
    treatment:   # log, symlog, logit

autogluon:
  fit:
    presets: medium_quality

num_plot_samples: 50
seed: 42
