defaults:
  - _self_
  - data:

data:
  base_name: ???
  data_path: ???
  graph_path: ???
  covariates: null
  outcome: ???
  treament: ???
  index_col: null # can overwrite
  treatment_max_bins: 100  # for binary bins will be 2
  has_coordinates: ???

  scaling:  # scaling done before transforms
    outcome:  # unit, standard
    treatment:  # unit, standard

  transforms:
    outcome:   # log, symlog, logit
    treatment:   # log, symlog, logit


autogluon:
  fit:
    presets: medium_quality

num_plot_samples: 50
seed: 42
debug_subsample:  # for quicker debugging set to a small number