defaults:
  - _self_
  - data:

data:
  path: ???
  confounder: null
  outcome: ???
  treaments: ???
  index_col: null # can overwrite
  continuous: ???  # if false, then assumed discrete

  scaling:  # scaling done before transforms
    outcome:  # unit, standard
    treatment:  # unit, standard

  transforms:
    outcome:   # log, symlog, logit
    treatment:   # log, symlog, logit

autogluon:
  fit:
    presets: medium_quality

continuous_treatment_bins: 100
num_plot_samples: 50
seed: 42
