defaults:
  - _self_
  - spaceenv: ???
  - space_dataverse.yaml

spaceenv:
  base_name: ???
  data_path: ???
  graph_path: ???
  covariates: null
  outcome: ???
  treament: ???
  index_col: 0
  treatment_max_bins: 100  # for binary bins will be 2

  scaling:  # scaling done before transforms
    outcome:  # unit, standard
    treatment:  # unit, standard
    covariates:

  transforms:
    outcome:   # log, symlog, logit
    treatment:   # log, symlog, logit
    covariates:
  
  boost_treatment: true  # replicate treatment cols during training
  # boosting preserves the outcome of importance, it will be replicated
  # as many times as other covariates are there.

  seed: 42

  autogluon:
    fit:
      presets: best_quality
      time_limit: 300
    feat_importance:
      time_limit: 120

  spatial_tuning:  
    frac: 0.02  # usually this will results 50 train, 16 val
    levels: 1
    buffer: 1

num_plot_samples: 50
debug_subsample:  # for quicker debugging set to a small number

hydra:
  run:
    dir: outputs/${spaceenv.base_name}
  job:
    chdir: true
