defaults:
  - _self_
  - spaceenv: ???

spaceenv:
  base_name: ${hydra:runtime.choices.spaceenv}
  covariates: null
  outcome: ???
  treament: ???
  index_col: 0
  treatment_max_bins: 100  # for binary bins will be 2

  scaling:  # scaling done before transforms
    outcome:  # unit, standard
    treatment:  # unit, standard
    covariates:

  transforms:
    outcome:   # log, symlog, logit
    treatment:   # log, symlog, logit
    covariates:
  
  boost_treatment: false  # replicate treatment cols during training
  # boosting preserves the outcome of importance, it will be replicated
  # as many times as other covariates are there.

  seed: 42

  autogluon:
    fit:
      presets: best_quality
      time_limit: 3600  # in seconds, null means no limit
                        # this paremeter can be overriden in the
                        # config of each spaceenv for complex envs.
                        # similarly with the time limits below, presets
                        # and hyperparmeters
      hyperparameters: null
    leave_out_fit:  # used for confounding scores
      presets: best_quality
      time_limit: 3600
      hyperparameters: null
    feat_importance:
      time_limit: 3600

  spatial_tuning:  
    init_frac: 0.05  # usually 35-50% train with 2 levels/buffer
    levels: 2
    buffer: 0

num_plot_samples: 50
debug_subsample:  # for quicker debugging set to a small number

hydra:
  run:
    dir: trained_spaceenvs/${spaceenv.base_name}
  job:
    chdir: true
